version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gradle-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/genesis-core/src/main/resources/data_genesis/frontend/skeletoons/angular/angular-skeletoon"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/genesis-core/src/main/resources/data_genesis/frontend/skeletoons/react/react-ts-skeletoon"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
