package org.labs.genesis.connexion.model;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.labs.genesis.config.langage.generator.framework.FrameworkMetadataProvider;
import org.labs.genesis.connexion.Database;
import org.labs.genesis.engine.GenesisTemplateEngine;
import org.labs.genesis.frontend.FrontendLanguage;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@Setter
@Getter
@ToString
public class ColumnMetadata {
    private String name;
    private String type;
    private String frontEndType;
    private String uiType;
    private String frontEndReferencedColumnType;
    private String databaseColumnType;
    private boolean primary;
    private boolean autoGenerated;
    private boolean foreign;
    private String referencedTable;
    private String columnType;
    private String referencedColumn;
    private String referencedColumnType;
    private String referencedPrimaryKeyColumn;
    private boolean unique;
    private boolean nullable;
    private boolean isNumeric;
    private boolean isNumericWithPrecision;
    private boolean isText;
    private boolean isDate;
    private boolean isTime;
    private boolean isTimeTz;
    private boolean isDateTime;
    private boolean isDateTimeTz;
    private boolean useTimeZone;
    private boolean isInterval;
    private String defaultValue;
    private int decimalDigits;
    private int columnSize;
    private Boolean isParentForeignKey = false;
    private Map<String, Object> validationAnnotations = new HashMap<>();

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;

        ColumnMetadata other = (ColumnMetadata) obj;

        boolean same = true;

        same = same && Objects.equals(this.name, other.name);
        same = same && Objects.equals(this.type, other.type);
        same = same && Objects.equals(this.databaseColumnType, other.databaseColumnType);
        same = same && Objects.equals(this.referencedTable, other.referencedTable);
        same = same && Objects.equals(this.columnType, other.columnType);
        same = same && Objects.equals(this.referencedColumn, other.referencedColumn);
        same = same && Objects.equals(this.referencedColumnType, other.referencedColumnType);
        same = same && Objects.equals(this.referencedPrimaryKeyColumn, other.referencedPrimaryKeyColumn);
        same = same && Objects.equals(this.defaultValue, other.defaultValue);

        same = same && this.primary == other.primary;
        same = same && this.autoGenerated == other.autoGenerated;
        same = same && this.foreign == other.foreign;
        same = same && this.unique == other.unique;
        same = same && this.nullable == other.nullable;
        same = same && this.isNumeric == other.isNumeric;
        same = same && this.isNumericWithPrecision == other.isNumericWithPrecision;
        same = same && this.isText == other.isText;
        same = same && this.isDate == other.isDate;
        same = same && this.isTime == other.isTime;
        same = same && this.isTimeTz == other.isTimeTz;
        same = same && this.isDateTime == other.isDateTime;
        same = same && this.isDateTimeTz == other.isDateTimeTz;
        same = same && this.useTimeZone == other.useTimeZone;
        same = same && this.isInterval == other.isInterval;

        same = same && this.decimalDigits == other.decimalDigits;
        same = same && this.columnSize == other.columnSize;

        same = same && Objects.equals(this.isParentForeignKey, other.isParentForeignKey);
        same = same && Objects.equals(this.validationAnnotations, other.validationAnnotations);

        return same;
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, type, frontEndType, uiType, frontEndReferencedColumnType,
                databaseColumnType, primary, autoGenerated, foreign, referencedTable, columnType,
                referencedColumn, referencedColumnType, referencedPrimaryKeyColumn,
                unique, nullable, isNumeric, isNumericWithPrecision, isText, isDate,
                isTime, isTimeTz, isDateTime, isDateTimeTz, useTimeZone, isInterval,
                defaultValue, decimalDigits, columnSize, isParentForeignKey, validationAnnotations);
    }

    public void setFrontEndType(FrontendLanguage frontendLanguage, Database database)
    {
        this.frontEndType = frontendLanguage.getTypes().get(database.getTypes().get(columnType));
        setUiType(frontendLanguage);
    }

    public void setFrontEndReferencedColumnType(FrontendLanguage frontendLanguage, Database database)
    {
        this.frontEndReferencedColumnType = frontendLanguage.getTypes().get(database.getTypes().get(databaseColumnType));
    }

    public void setUiType(FrontendLanguage frontendLanguage)
    {
        setUiType(frontendLanguage.getInputTypes().get(this.getFrontEndType()));
    }

    private void setUiType(String uiType)
    {
        this.uiType = uiType;
    }

    public void setNullable(String nullable, Map<String, Object> frameworkValidationAnnotations, GenesisTemplateEngine engine) throws Exception {
        if(nullable.equalsIgnoreCase("YES")){
            this.nullable = true;
            return;
        }
        this.nullable = false;
        Map<String, Object> safeValidationAnnotations = Objects.requireNonNullElse(frameworkValidationAnnotations, new HashMap<>());
        Map<String, Object> fieldHashMap = FrameworkMetadataProvider.getFieldHashMap(this);
        String annotationTemplate = (String) safeValidationAnnotations.getOrDefault("notNull","{{removeLine}}");
        String annotationResult = engine.render(annotationTemplate, fieldHashMap);
        this.validationAnnotations.put("notNull",annotationResult);
    }

    public void setDefaultValue(String defaultValue, Map<String, Object> frameworkValidationAnnotations, GenesisTemplateEngine engine) throws Exception {
        this.defaultValue = defaultValue;
        if (defaultValue!=null &&
                (!this.isDate
                || !this.isTime
                || !this.isDateTime
                || !this.isInterval)
            )
        {
            Map<String, Object> safeValidationAnnotations = Objects.requireNonNullElse(frameworkValidationAnnotations, new HashMap<>());
            Map<String, Object> fieldHashMap = FrameworkMetadataProvider.getFieldHashMap(this);
            String annotationTemplate = (String) safeValidationAnnotations.getOrDefault("defaultValue","{{removeLine}}");
            String annotationResult = engine.render(annotationTemplate, fieldHashMap);
            this.validationAnnotations.put("defaultValue",annotationResult);
        }
    }

    public void setColumnSize(int columnSize, Map<String, Object> frameworkValidationAnnotations, GenesisTemplateEngine engine) throws Exception {
        this.columnSize = columnSize;
        if (this.isText) {
            Map<String, Object> safeValidationAnnotations = Objects.requireNonNullElse(frameworkValidationAnnotations, new HashMap<>());
            Map<String, Object> fieldHashMap = FrameworkMetadataProvider.getFieldHashMap(this);
            String annotationTemplate = (String) safeValidationAnnotations.getOrDefault("maxSize","{{removeLine}}");
            String annotationResult = engine.render(annotationTemplate, fieldHashMap);
            this.validationAnnotations.put("maxSize",annotationResult);
        }
    }

    public void setDecimalDigits(int decimalDigits, Map<String, Object> frameworkValidationAnnotations, GenesisTemplateEngine engine) throws Exception {
        this.decimalDigits = decimalDigits;
        if(this.isNumericWithPrecision){
            Map<String, Object> safeValidationAnnotations = Objects.requireNonNullElse(frameworkValidationAnnotations, new HashMap<>());
            Map<String, Object> fieldHashMap = FrameworkMetadataProvider.getFieldHashMap(this);
            String annotationTemplate = (String) safeValidationAnnotations.getOrDefault("digits","{{removeLine}}");
            String annotationResult = engine.render(annotationTemplate, fieldHashMap);
            this.validationAnnotations.put("digits",annotationResult);
        }
    }

    public void removeSeparateMinMaxAnnotations(){
        this.validationAnnotations.remove("numericMaximumInclusiveValue");
        this.validationAnnotations.remove("numericMinimumInclusiveValue");
        this.validationAnnotations.remove("numericMaximumValue");
        this.validationAnnotations.remove("numericMinimumValue");
    }

    public void checkAndCreateRangeAnnotation(Map<String, Object> frameworkValidationAnnotations,
                                              Map<String, Object> fieldHashMap,
                                              GenesisTemplateEngine engine,
                                              String currentValue,
                                              boolean isMin) throws Exception {
        Map<String, Object> safeValidationAnnotations = Objects.requireNonNullElse(frameworkValidationAnnotations, new HashMap<>());
        if ((isMin && hasMaxConstraint()) || (!isMin && hasMinConstraint())) {
            if (safeValidationAnnotations.containsKey("numericMinimumAndMaximumValue")) {
                Object otherValue = getOppositeBoundValue(isMin);
                if (otherValue != null) {
                    String annotationTemplate = (String) safeValidationAnnotations.getOrDefault("numericMinimumAndMaximumValue", "{{removeLine}}");
                    fieldHashMap.put("minValue", isMin ? currentValue : otherValue);
                    fieldHashMap.put("maxValue", isMin ? otherValue : currentValue);
                    String annotationResult = engine.render(annotationTemplate, fieldHashMap);
                    validationAnnotations.put("numericMinimumAndMaximumValue", annotationResult);
                    removeSeparateMinMaxAnnotations();
                }
            }
        }
    }

    private Object getOppositeBoundValue(boolean isMin) {
        if (isMin) {
            return validationAnnotations.containsKey("numericMaximumInclusiveValue")
                    ? validationAnnotations.get("numericMaximumInclusiveValueData")
                    : validationAnnotations.get("numericMaximumValueData");
        } else {
            return validationAnnotations.containsKey("numericMinimumInclusiveValue")
                    ? validationAnnotations.get("numericMinimumInclusiveValueData")
                    : validationAnnotations.get("numericMinimumValueData");
        }
    }

    private boolean hasMinConstraint() {
        return validationAnnotations.containsKey("numericMinimumInclusiveValue")
                || validationAnnotations.containsKey("numericMinimumValue");
    }

    private boolean hasMaxConstraint() {
        return validationAnnotations.containsKey("numericMaximumInclusiveValue")
                || validationAnnotations.containsKey("numericMaximumValue");
    }

    public void checkAndCreateNotNullNotBlankCombinedAnnotation(
            Map<String, Object> frameworkValidationAnnotations,
            Map<String, Object> fieldHashMap,
            GenesisTemplateEngine engine) throws Exception {
        Map<String, Object> safeValidationAnnotations = Objects.requireNonNullElse(frameworkValidationAnnotations, new HashMap<>());
        if (validationAnnotations.containsKey("notNull")
                && safeValidationAnnotations.containsKey("notNullAndNotBlank")) {

            String annotationTemplate = (String) safeValidationAnnotations.getOrDefault(
                    "notNullAndNotBlank", "{{removeLine}}"
            );
            String annotationResult = engine.render(annotationTemplate, fieldHashMap);
            validationAnnotations.put("notNullAndNotBlank", annotationResult);
            validationAnnotations.remove("notNull");
            validationAnnotations.remove("notBlank");
        }
    }
}
