- fileType: "Docker compose"
  fileName: "docker-compose"
  extension: "yml"
  content : |
    services:
      {{#if isFrontendDockerized}}${frontendContainer}:
        build:
          context: ./${frontendDir}
          dockerfile: Dockerfile
        container_name: frontend
        ports:
          - "${frontendPort}:${frontendPort}"
        volumes:
          - ./${frontendDir}:/app
          {{#each frontendVolumes}}- ${this.name}:${this.dir}{{/each}}
        {{#if hadFrontendEnvironments}}environment:{{#each frontendEnvironments}}
          - ${this.name}${this.separator}${this.value}{{/each}}{{/if}}
        depends_on:
          - backend{{/if}}
      {{#if isBackendDockerized}}${backendContainer}:
        build:
          context: ./${backendDir}
          dockerfile: Dockerfile
        container_name: backend
        ports:
          - "${backendPort}:${backendPort}"
        volumes:
          - ./${backendDir}:/app
          {{#each volumes}}- ${this.name}:${this.dir}{{/each}}
        {{#if hadEnvironments}}environment:{{#each environments}}
          - ${this.name}${this.separator}${this.value}{{/each}}{{/if}}
        extra_hosts:
          - "host.docker.internal:host-gateway"{{/if}}
    {{#if hadVolumes}}volumes:{{/if}}
      {{#if isBackendDockerized}}{{#each volumes}}${this.name}:{{/each}}{{/if}}
      {{#if isFrontendDockerized}}{{#each frontendVolumes}}${this.name}:{{/each}}{{/if}}
  destinationPath: ""
